services:
  backend:
    image: 969759464709.dkr.ecr.eu-north-1.amazonaws.com/production-ec2-infrastructure-backend:v1
    container_name: backend
    env_file:
      - /opt/stan/.env
    expose:
      - "3500"
    depends_on:
      - mongo-extra

  frontend:
    image: 969759464709.dkr.ecr.eu-north-1.amazonaws.com/production-ec2-infrastructure-frontend:v1
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  mongo-extra:
    image: mongo:6
    container_name: mongo-extra
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
