events {}

http {
  server {
    listen 80;

    # FRONTEND
    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # BACKEND
    location /api/ {
      proxy_pass http://backend:3500/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
